(setq vc-handled-backends nil)

(when (< emacs-major-version 24)
  (add-to-list 'load-path "~/.emacs.d/"))
(require 'package)
(setq package-archives '(("marmalade" . "http://marmalade-repo.org/packages/")
                         ("melpa" . "http://melpa.milkbox.net/packages/")))
(package-initialize)

(when (not package-archive-contents)
  (package-refresh-contents))

(defvar daf-packages '(popup
		       auto-complete
                       undo-tree
                       evil
                       evil-leader
                       magit
                       yasnippet
                       color-theme-solarized
                       twilight-theme
                       pony-mode
                       paredit
                       evil-paredit
                       geiser))
(dolist (p daf-packages)
  (when (not (package-installed-p p))
    (package-install p)))


;; initialize plugins
(add-to-list 'load-path "~/.emacs.d/plugin/emacs-daylight")
(require 'daylight)
(require 'popup)
(require 'auto-complete-config)
(require 'evil-leader)
(require 'evil-paredit)
;; (require 'pony-mode)
(ac-config-default)
(evil-mode 1)
(yas-global-mode 1)


;; load settings -- wait for packages to load first (emacswiki.org/emacs/ELPA)
(add-hook 'after-init-hook
          #'(lambda ()
	      (add-to-list 'load-path "~/.emacs.d/config")
              (require 'daf-daylight)
	      (require 'daf-yas)
	      (require 'daf-evil)
	      (require 'daf-evil-leader)
	      (require 'daf-mode-hooks)
	      (require 'daf-global-settings)
	      (require 'luke-funcs)))


;;;;;;;;;;;;;;;;;;;
;; Autogenerated ;;
;;;;;;;;;;;;;;;;;;;

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-names-vector ["black" "#d55e00" "#009e73" "#f8ec59" "#0072b2" "#cc79a7" "#56b4e9" "white"])
 '(c-basic-offset 4)
 '(column-number-mode t)
 '(custom-safe-themes (quote ("5e1d1564b6a2435a2054aa345e81c89539a72c4cad8536cfe02583e0b7d5e2fa" "1e7e097ec8cb1f8c3a912d7e1e0331caeed49fef6cff220be63bd2a6ba4cc365" "27470eddcaeb3507eca2760710cc7c43f1b53854372592a3afa008268bcf7a75" "6cfe5b2f818c7b52723f3e121d1157cf9d95ed8923dbc1b47f392da80ef7495d" "fc5fcb6f1f1c1bc01305694c59a1a861b008c534cae8d0e48e4d5e81ad718bc6" default)))
 '(fringe-mode (quote (nil . 0)) nil (fringe))
 '(indicate-buffer-boundaries (quote left))
 '(indicate-empty-lines t)
 '(inhibit-startup-screen nil)
 '(initial-buffer-choice nil)
 '(show-paren-mode t)
 '(size-indication-mode t))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
