(deftheme solarized-dark
  "Created 2013-02-15.")

(custom-theme-set-variables
 'solarized-dark
 )

(custom-theme-set-faces
 'solarized-dark
 '(cursor ((t (:foreground "#1c1c1c" :background "#808080"))))
 '(error ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#d70000"))))
 '(escape-glyph-face ((t (:foreground "#d70000"))))
 '(fringe ((t (:foreground "#585858" :background "#262626"))))
 '(linum ((t (:background "color-234" :foreground "#585858"))))
 '(header-line ((t (:foreground "#808080" :background "#262626" :weight normal :slant normal :underline nil :inverse-video t))))
 '(highlight ((t (:background "#262626"))))
 '(hl-line ((t (:underline nil :background "#262626"))))
 '(isearch ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#d75f00" :background "#1c1c1c"))))
 '(isearch-fail ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#d75f00" :background "#1c1c1c"))))
 '(lazy-highlight ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#af8700" :background "#1c1c1c"))))
 '(link ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#5f5faf"))))
 '(link-visited ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#af005f"))))
 '(menu ((t (:foreground "#808080" :background "#262626"))))
 '(minibuffer-prompt ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#00afaf"))))
 '(mode-line ((t (:foreground "#8a8a8a" :background "#262626" :weight normal :slant normal :underline nil :inverse-video t :box nil))))
 '(mode-line-inactive ((t (:foreground "#626262" :background "#262626" :weight normal :slant normal :underline nil :inverse-video t :box nil))))
 '(region ((t (:foreground "#585858" :background "#1c1c1c" :weight normal :slant normal :underline nil :inverse-video t))))
 '(secondary-selection ((t (:background "#262626"))))
 '(shadow ((t (:foreground "#585858"))))
 '(trailing-whitespace ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#d70000"))))
 '(vertical-border ((t nil)))
 '(comint-highlight-prompt ((t (:foreground "#0087ff"))))
 '(compilation-info ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#5f8700"))))
 '(compilation-warning ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#d75f00"))))
 '(custom-button ((t (:foreground "#8a8a8a" :background "#262626" :box (:line-width 2 :style released-button)))))
 '(custom-button-mouse ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#8a8a8a" :background "#262626" :inherit custom-button))))
 '(custom-button-pressed ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#8a8a8a" :background "#262626" :box (:line-width 2 :style pressed-button) :inherit custom-button-mouse))))
 '(custom-changed ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#0087ff" :background "#ffffd7"))))
 '(custom-comment ((t (:foreground "#8a8a8a" :background "#262626"))))
 '(custom-comment-tag ((t (:foreground "#8a8a8a" :background "#262626"))))
 '(custom-documentation ((t (:inherit default))))
 '(custom-group-tag ((t (:foreground "#8a8a8a"))))
 '(custom-group-tag-1 ((t ((:weight bold :slant normal :underline nil :inverse-video nil) :foreground "#8a8a8a"))))
 '(custom-invalid ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#d70000" :background "#1c1c1c"))))
 '(custom-link ((t (:foreground "#5f5faf"))))
 '(custom-state ((t (:foreground "#5f8700"))))
 '(custom-variable-tag ((t (:foreground "#8a8a8a"))))
 '(diff-added ((t (:foreground "#5f8700"))))
 '(diff-changed ((t (:foreground "#af8700"))))
 '(diff-removed ((t (:foreground "#d70000"))))
 '(diff-refine-change ((t (:foreground "#0087ff" :background "#1c1c1c"))))
 '(diff-file-header ((t (:background "#1c1c1c"))))
 '(diff-header ((t (:foreground "#8a8a8a" :background "#1c1c1c"))))
 '(ido-only-match ((t (:foreground "#5f8700"))))
 '(ido-subdir ((t (:foreground "#0087ff"))))
 '(ido-first-match ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#5f8700"))))
 '(emacs-wiki-bad-link-face ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#d70000"))))
 '(emacs-wiki-link-face ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#0087ff"))))
 '(emacs-wiki-verbatim-face ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#626262"))))
 '(eshell-ls-archive ((t (:foreground "#af005f"))))
 '(eshell-ls-backup ((t (:foreground "#af8700"))))
 '(eshell-ls-clutter ((t (:foreground "#d75f00"))))
 '(eshell-ls-directory ((t (:foreground "#0087ff"))))
 '(eshell-ls-executable ((t (:foreground "#5f8700"))))
 '(eshell-ls-missing ((t (:foreground "#d70000"))))
 '(eshell-ls-product ((t (:foreground "#af8700"))))
 '(eshell-ls-readonly ((t (:foreground "#8a8a8a"))))
 '(eshell-ls-special ((t (:foreground "#5f5faf"))))
 '(eshell-ls-symlink ((t (:foreground "#00afaf"))))
 '(eshell-ls-unreadable ((t (:foreground "#626262"))))
 '(eshell-prompt ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#5f8700"))))
 '(font-lock-builtin-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#5f8700"))))
 '(font-lock-comment-face ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#585858"))))
 '(font-lock-constant-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#00afaf"))))
 '(font-lock-function-name-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#0087ff"))))
 '(font-lock-keyword-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#5f8700"))))
 '(font-lock-string-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#00afaf"))))
 '(font-lock-type-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#af8700"))))
 '(font-lock-variable-name-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#0087ff"))))
 '(font-lock-warning-face ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#d70000"))))
 '(font-lock-doc-face ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#585858"))))
 '(font-lock-doc-string-face ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#585858"))))
 '(font-lock-color-constant-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#5f8700"))))
 '(font-lock-comment-delimiter-face ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#585858"))))
 '(font-lock-preprocessor-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#d75f00"))))
 '(font-lock-reference-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#00afaf"))))
 '(font-lock-negation-char-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#d70000"))))
 '(font-lock-other-type-face ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#0087ff"))))
 '(font-lock-regexp-grouping-construct ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#d75f00"))))
 '(font-lock-special-keyword-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#d70000"))))
 '(font-lock-exit-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#d70000"))))
 '(font-lock-other-emphasized-face ((t (:weight bold :underline nil :inverse-video nil :foreground "#5f5faf"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#af8700"))))
 '(info-xref ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#0087ff"))))
 '(info-xref-visited ((t (:foreground "#af005f" :inherit info-xref))))
 '(org-hide ((t (:foreground "#1c1c1c"))))
 '(org-todo ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#1c1c1c" :background "#d70000"))))
 '(org-done ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#5f8700"))))
 '(org-todo-kwd-face ((t (:foreground "#d70000" :background "#1c1c1c"))))
 '(org-done-kwd-face ((t (:foreground "#5f8700" :background "#1c1c1c"))))
 '(org-project-kwd-face ((t (:foreground "#5f5faf" :background "#1c1c1c"))))
 '(org-waiting-kwd-face ((t (:foreground "#d75f00" :background "#1c1c1c"))))
 '(org-someday-kwd-face ((t (:foreground "#0087ff" :background "#1c1c1c"))))
 '(org-started-kwd-face ((t (:foreground "#af8700" :background "#1c1c1c"))))
 '(org-cancelled-kwd-face ((t (:foreground "#5f8700" :background "#1c1c1c"))))
 '(org-delegated-kwd-face ((t (:foreground "#00afaf" :background "#1c1c1c"))))
 '(table-cell ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#808080" :background "#1c1c1c"))))
 '(outline-1 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#0087ff"))))
 '(outline-2 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#00afaf"))))
 '(outline-3 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#af8700"))))
 '(outline-4 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#d70000"))))
 '(outline-5 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#808080"))))
 '(outline-6 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#585858"))))
 '(outline-7 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#d75f00"))))
 '(outline-8 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#5f5faf"))))
 '(speedbar-button-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#8a8a8a"))))
 '(speedbar-directory-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#d75f00"))))
 '(speedbar-file-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#5f8700"))))
 '(speedbar-highlight-face ((t (:background "#262626"))))
 '(speedbar-selected-face ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#af8700"))))
 '(speedbar-separator-face ((t (:weight normal :slant normal :underline nil :inverse-video t))))
 '(speedbar-tag-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#0087ff"))))
 '(show-paren-match ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#00afaf" :background "#262626"))))
 '(show-paren-mismatch ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#d70000" :background "#585858"))))
 '(widget-field ((t (:foreground "#8a8a8a" :background "#262626" :box (:line-width 1) :inherit default))))
 '(widget-single-line-field ((t (:inherit widget-field))))
 '(flymake-errline ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#d70000" :background "#1c1c1c"))))
 '(flymake-warnline ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#d70000" :background "#1c1c1c"))))
 '(column-marker-1 ((t (:background "#585858"))))
 '(column-marker-2 ((t (:background "#00afaf"))))
 '(column-marker-3 ((t (:background "#5f5faf"))))
 '(jabber-activity-face ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#d70000"))))
 '(jabber-activity-personal-face ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#0087ff"))))
 '(jabber-chat-error ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#d70000"))))
 '(jabber-chat-prompt-foreign ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#d70000"))))
 '(jabber-chat-prompt-local ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#0087ff"))))
 '(jabber-chat-prompt-system ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#5f8700"))))
 '(jabber-chat-text-foreign ((t (:foreground "#8a8a8a"))))
 '(jabber-chat-text-local ((t (:foreground "#808080"))))
 '(jabber-chat-rare-time-face ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#5f8700"))))
 '(jabber-roster-user-away ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#5f8700"))))
 '(jabber-roster-user-chatty ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#d75f00"))))
 '(jabber-roster-user-dnd ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#d70000"))))
 '(jabber-roster-user-error ((t (:weight light :slant italic :foreground "#d70000"))))
 '(jabber-roster-user-offline ((t (:foreground "#585858"))))
 '(jabber-roster-user-online ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#0087ff"))))
 '(jabber-roster-user-xa ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#af005f"))))
 '(gnus-cite-1 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#0087ff"))))
 '(gnus-cite-2 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#00afaf"))))
 '(gnus-cite-3 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#af8700"))))
 '(gnus-cite-4 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#d70000"))))
 '(gnus-cite-5 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#d75f00"))))
 '(gnus-cite-6 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#5f5faf"))))
 '(gnus-cite-7 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#5f8700"))))
 '(gnus-cite-8 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#af005f"))))
 '(gnus-cite-9 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#626262"))))
 '(gnus-cite-10 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#585858"))))
 '(gnus-cite-11 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#262626"))))
 '(gnus-group-mail-1 ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#ffffd7"))))
 '(gnus-group-mail-1-empty ((t (:foreground "#ffffd7"))))
 '(gnus-group-mail-2 ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#e4e4e4"))))
 '(gnus-group-mail-2-empty ((t (:foreground "#e4e4e4"))))
 '(gnus-group-mail-3 ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#af005f"))))
 '(gnus-group-mail-3-empty ((t (:foreground "#af005f"))))
 '(gnus-group-mail-low ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#626262"))))
 '(gnus-group-mail-low-empty ((t (:foreground "#626262"))))
 '(gnus-group-news-1 ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#8a8a8a"))))
 '(gnus-group-news-1-empty ((t (:foreground "#8a8a8a"))))
 '(gnus-group-news-2 ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#0087ff"))))
 '(gnus-group-news-2-empty ((t (:foreground "#0087ff"))))
 '(gnus-group-news-low ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#5f5faf"))))
 '(gnus-group-news-low-empty ((t (:foreground "#5f5faf"))))
 '(gnus-emphasis-highlight-words ((t (:weight normal :slant normal :underline nil :inverse-video nil (:foreground "#af8700")))))
 '(gnus-header-content ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#585858"))))
 '(gnus-header-from ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#626262"))))
 '(gnus-header-name ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#585858"))))
 '(gnus-header-newsgroups ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#262626"))))
 '(gnus-header-subject ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#0087ff"))))
 '(gnus-server-agent ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#ffffd7"))))
 '(gnus-server-closed ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#8a8a8a"))))
 '(gnus-server-denied ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#e4e4e4"))))
 '(gnus-server-offline ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#5f8700"))))
 '(gnus-server-opened ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#00afaf"))))
 '(gnus-signature ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#585858"))))
 '(gnus-splash ((t (:foreground "#e4e4e4"))))
 '(gnus-summary-cancelled ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#d70000"))))
 '(gnus-summary-high-ancient ((t (:weight bold :slant normal :underline nil :inverse-video nil :inherit gnus-summary-normal-ancient))))
 '(gnus-summary-high-read ((t (:weight bold :slant normal :underline nil :inverse-video nil :inherit gnus-summary-normal-read))))
 '(gnus-summary-high-ticked ((t (:weight bold :slant normal :underline nil :inverse-video nil :inherit gnus-summary-normal-ticked))))
 '(gnus-summary-high-undownloaded ((t (:weight bold :slant normal :underline nil :inverse-video nil :inherit gnus-summary-normal-undownloaded))))
 '(gnus-summary-high-unread ((t (:weight bold :slant normal :underline nil :inverse-video nil :inherit gnus-summary-normal-unread))))
 '(gnus-summary-low-ancient ((t (:weight normal :slant italic :underline nil :inverse-video nil :inherit gnus-summary-normal-ancient))))
 '(gnus-summary-low-read ((t (:weight normal :slant italic :underline nil :inverse-video nil :inherit gnus-summary-normal-ancient))))
 '(gnus-summary-low-unread ((t (:weight normal :slant italic :underline nil :inverse-video nil :inherit gnus-summary-normal-unread))))
 '(gnus-summary-low-ticked ((t (:weight normal :slant italic :underline nil :inverse-video nil :inherit gnus-summary-normal-ancient))))
 '(gnus-summary-low-undownloaded ((t (:weight normal :slant italic :underline nil :inverse-video nil :inherit gnus-summary-normal-ancient))))
 '(gnus-summary-normal-ancient ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#0087ff"))))
 '(gnus-summary-normal-read ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#585858"))))
 '(gnus-summary-normal-ticked ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#d70000"))))
 '(gnus-summary-normal-undownloaded ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#e4e4e4"))))
 '(gnus-summary-normal-unread ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#0087ff"))))
 '(gnus-summary-selected ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#1c1c1c" :background "#af8700"))))
 '(message-mml ((t (:foreground "#0087ff"))))
 '(message-cited-text ((t (:foreground "#e4e4e4"))))
 '(message-separator ((t (:foreground "#ffffd7"))))
 '(message-header-xheader ((t (:foreground "#5f5faf"))))
 '(message-header-name ((t (:foreground "#00afaf"))))
 '(message-header-other ((t (:foreground "#d70000"))))
 '(message-header-newsgroups ((t (:weight bold :underline nil :inverse-video nil :foreground "#af8700"))))
 '(message-header-subject ((t (:foreground "#626262"))))
 '(message-header-cc ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#5f8700"))))
 '(message-header-to ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#8a8a8a"))))
 '(paren-face ((t (:foreground "#585858"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#00afaf"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#af8700"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#0087ff"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#d70000"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#5f8700"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#0087ff"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#d75f00"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#af005f"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#808080"))))
 '(slime-error-face ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#d70000"))))
 '(slime-note-face ((t (:foreground "#af8700"))))
 '(slime-repl-inputted-output-face ((t (:foreground "#d70000"))))
 '(slime-repl-output-mouseover-face ((t (:box (:color "#ffffd7")))))
 '(slime-style-warning-face ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#d75f00"))))
 '(slime-warning-face ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#d70000"))))
 '(whitespace-empty ((t (:foreground "#d70000"))))
 '(whitespace-hspace ((t (:foreground "#d75f00"))))
 '(whitespace-indentation ((t (:foreground "#262626"))))
 '(whitespace-space ((t (:foreground "#262626"))))
 '(whitespace-space-after-tab ((t (:foreground "#00afaf"))))
 '(whitespace-space-before-tab ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#d70000"))))
 '(whitespace-tab ((t (:foreground "#262626"))))
 '(whitespace-trailing ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#d70000" :background "#262626"))))
 '(whitespace-highlight-face ((t (:foreground "#d70000" :background "#0087ff"))))
 '(whitespace-line ((t (:foreground "#af005f" :background "#1c1c1c"))))
 '(rcirc-my-nick ((t (:foreground "#0087ff"))))
 '(rcirc-nick-in-message ((t (:foreground "#d75f00"))))
 '(rcirc-other-nick ((t (:foreground "#5f8700"))))
 '(rcirc-prompt ((t (:foreground "#af8700"))))
 '(rcirc-bright-nick ((t (:foreground "#af005f"))))
 '(rcirc-server ((t (:foreground "#8a8a8a"))))
 '(rcirc-timestamp ((t (:foreground "#585858"))))
 '(erc-input-face ((t (:foreground "#585858"))))
 '(erc-keyword-face ((t (:weight bold :underline nil :inverse-video nil :foreground "#af8700"))))
 '(erc-my-nick-face ((t (:foreground "#0087ff"))))
 '(erc-nick-default-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#00afaf"))))
 '(erc-notice-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#0087ff"))))
 '(erc-timestamp-face ((t (:foreground "#585858"))))
 '(font-latex-warning-face ((t (:foreground "#d70000"))))
 '(font-latex-sectioning-5-face ((t (:foreground "#5f5faf"))))
 '(flyspell-incorrect ((t (:foreground "#d70000"))))
 '(flyspell-duplicate ((t (:foreground "#af8700"))))
 '(default ((t (:background "#1c1c1c" :foreground "#808080")))))

(provide-theme 'solarized-dark)
